[build]
  command = "echo Building 6nr functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/kaithhealth"
  to = "/.netlify/functions/api/kaithhealth"
  status = 200
  force = true
